
steps:
- task: AzureImageBuilder.devOps-task-for-azure-image-builder.custom-build-release-task.AzureImageBuilderTask@1
  displayName: 'Azure VM Image Builder Task'
  inputs:
    managedIdentity: '/subscriptions/cbf8b966-9488-4fc7-a133-b65c3b0285a8/resourceGroups/testrg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/testmangedid'
    imageSource: marketplace
    baseImage: 'MicrosoftWindowsDesktop:Windows-10:19h1-evd'
    baseImagePubOfferSku: 'MicrosoftWindowsDesktop:windows-10:20h2-evd '
    provisioner: 'powershell'
    windowsUpdateProvisioner: true
    packagePath: '$(System.DefaultWorkingDirectory)/_WVD_POC/WVD'
    inlineScript: '''& set-executionpolicy remotesigned -scope Process -Force; c:\BuildArtifacts\WVD\win10.ps1'''
    storageAccountName: 'testzsq'
    distributeType: sig
    galleryImageId: '/subscriptions/cbf8b966-9488-4fc7-a133-b65c3b0285a8/resourceGroups/testrg/providers/Microsoft.Compute/galleries/imagegall'
    replicationRegions: 'westeurope,northeurope'
    ibSubscription: 'ALVENTECH (0000-0000-000-0000-00000000)'
    ibAzureResourceGroup: 'testrg'
    ibLocation:'uksouth'
    vmSize: 'Standard_D2s_v3'
