 steps:
  -task: AzureImageBuilderTask@1
  inputs:
    managedIdentity: '/subscriptions/cbf8b966-9488-4fc7-a133-b65c3b0285a8/resourceGroups/testrg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/testmangedid'
    imageSource: 'marketplace'
    baseImage: 'MicrosoftWindowsServer:WindowsServer:2019-Datacenter'
    provisioner: 'powershell'
    packagePath: '$(System.DefaultWorkingDirectory)'
    inlineScript: 'c:\buildartifacts'
    storageAccountName: 'testzsq'
    imageIdForDistribute: '/subscriptions/cbf8b966-9488-4fc7-a133-b65c3b0285a8/resourceGroups/testrg/providers/Microsoft.Compute/galleries/imagegall'
    managedImageLocation: 'uksouth'
    ibSubscription: 'anugrah pay as you go(cbf8b966-9488-4fc7-a133-b65c3b0285a8)'
    ibAzureResourceGroup: 'testrg'
    ibLocation: 'uksouth'